// 此处统一暴露接口请求的命名空间类型
export * as Auth from './api/auth'
export * as Upload from './api/common/upload'
export * as Dashboard from './api/dashboard'
export * as User from './api/system/user'
export * as Dict from './api/system/dict'
export * as Role from './api/system/role'
export * as Menu from './api/system/menu'
export * as Dept from './api/system/dept'
export * as File from './api/system/file'
export * as Cache from './api/monitor/cache'
export * as Server from './api/monitor/server'
export * as Loginlog from './api/monitor/loginlog'
export * as Online from './api/monitor/online-user'
export * as Operlog from './api/monitor/operlog'
export * as Job from './api/monitor/job'
export * as JobLog from './api/monitor/job-log'

// 此处统一暴露全局组件的类型
export * from '@/components/SvgIcon/types'
export * from '@/components/ProTable/types'
export * from '@/components/ProSearch/types'
export * from '@/components/RightToolbar/types'
